version: '3'
services:
  okapi:
    image: fluagen/okapi:4.7.2
    ports:
      - 9130:9130
      - 5005-5009:5005-5009
    container_name: okapi
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: "postgres:10.16"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata