version: '3'
services:
  okapi:
    build: .
    ports:
      - 9130:9130
      - 5005-5009:5005-5009
    container_name: okapi
    volumes:
      - ./repo/:/app/repo
      - ./init.d/:/app/init.d
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: "postgres"
    volumes:
      - ./db/init.d/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 111111
      PGDATA: /var/lib/postgresql/data/pgdata
